title: Mario Suarez
email: ms627@njit.edu
description: >- # this means to ignore newlines until "baseurl:"
  An NJIT Project for IS117
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: latinorebel
github_username:  mariolsuarez

# Build settings
sass:
  sass_dir: _sass
include:  ['_pages']
kramdown:
  input:  GFM